from django.conf import settings
from django.contrib.sites.models import Site
from django.contrib.redirects.models import Redirect
from djangoplicity.logger import define_logger
from djangoplicity.migration import run_migration
from djangoplicity.migration.apps.archives import ArchiveInitializationTask, \
	ArchiveMigrationTask, DataMapping
from djangoplicity.migration.apps.pages import PageInitializationTask, \
	PageMigrationTask, HTMLPageDocument
from djangoplicity.pages.models import Section
from djangoplicity.releases.models import Release
from djangoplicity.media.models import Image
from spacetelescope.archives.educational.models import *
from spacetelescope.archives.goodies.models import *
from spacetelescope.archives.products.models import *
from spacetelescope.migration.archives import *
from spacetelescope.migration.pages import SpacetelescopePageDocument
import logging

#
# Define logger to use
#
logger = define_logger( "migration_logger", level=logging.DEBUG, file_logging=False )
	
#
# Define configuration options
#
conf = {
	'pages' : {
				'root' : '/Volumes/webdocs/spacetelescope/docs/', 
				'site' : Site.objects.get(id=settings.SITE_ID), 
				'section' : Section.objects.get_or_create( name='Default', append_title='spacetelescope.org', template='pages/page_onecolumn.html' )[0] 
			  },
	'logger' : 'migration_logger', 
}

def choose_tasks():
	return archivetasks

#
# Define migration tasks
#
archivetasks = [
	# INIT
	ArchiveInitializationTask( Redirect ),
	
	
	ArchiveInitializationTask( Release ),
	ArchiveInitializationTask( Image ),
    
    # Goodies
    ArchiveInitializationTask( EducationalMaterial ),
    ArchiveInitializationTask( KidsDrawing ),
    ArchiveInitializationTask( Calendar ),
# OnlineArt
# OnlineArtAuthor
# Print Layout
    ArchiveInitializationTask( SlideShow ),
    
    #Products
    ArchiveInitializationTask( Book ),
    ArchiveInitializationTask( CDROM ),
    ArchiveInitializationTask( Brochure ),
    ArchiveInitializationTask( Merchandise ),
    ArchiveInitializationTask( Newsletter ),
    ArchiveInitializationTask( PostCard ),
    ArchiveInitializationTask( Poster ),
    ArchiveInitializationTask( PressKit ),
    ArchiveInitializationTask( Sticker ),

    
    #ORG
   
   
    # MIG
    ArchiveMigrationTask( SpacetelescopeCSVDataSource( '/Volumes/webdocs/spacetelescope/docs/csvfiles/newsdata.csv'), NewsDataMapping ),
	ArchiveMigrationTask( SpacetelescopeCSVDataSource( '/Volumes/webdocs/spacetelescope/docs/csvfiles/imagedata.csv'), ImagesDataMapping ),
	
	# Goodies
	ArchiveMigrationTask( SpacetelescopeCSVDataSource( '/Users/luis/Workspaces/pttu/spacetelescope.org/migration/csvfiles/edumatdata.csv'), EducationalMaterialsDataMapping ),
	ArchiveMigrationTask( SpacetelescopeCSVDataSource( '/Users/luis/Workspaces/pttu/spacetelescope.org/migration/csvfiles/kidsdrawingdata.csv'), KidsDrawingsDataMapping ),
	ArchiveMigrationTask( SpacetelescopeCSVDataSource( '/Users/luis/Workspaces/pttu/spacetelescope.org/migration/csvfiles/calendardata.csv'), CalendarsDataMapping ),
# OnlineArt
# OnlineArtAuthor
# Print Layout

    # Products
    ArchiveMigrationTask( SpacetelescopeCSVDataSource( '/Users/luis/Workspaces/pttu/spacetelescope.org/migration/csvfiles/slideshowdata.csv'), SlideShowDataMapping ),
    ArchiveMigrationTask( SpacetelescopeCSVDataSource( '/Users/luis/Workspaces/pttu/spacetelescope.org/migration/csvfiles/bookdata.csv'), BookDataMapping ),
    ArchiveMigrationTask( SpacetelescopeCSVDataSource( '/Users/luis/Workspaces/pttu/spacetelescope.org/migration/csvfiles/cdromdata.csv'), CDROMDataMapping ),
    ArchiveMigrationTask( SpacetelescopeCSVDataSource( '/Users/luis/Workspaces/pttu/spacetelescope.org/migration/csvfiles/brochuredata.csv'), BrochureDataMapping ),
    ArchiveMigrationTask( SpacetelescopeCSVDataSource( '/Users/luis/Workspaces/pttu/spacetelescope.org/migration/csvfiles/merchandisedata.csv'), MerchandiseDataMapping ),
    ArchiveMigrationTask( SpacetelescopeCSVDataSource( '/Users/luis/Workspaces/pttu/spacetelescope.org/migration/csvfiles/newsletterdata.csv'), NewsletterDataMapping ),
    ArchiveMigrationTask( SpacetelescopeCSVDataSource( '/Users/luis/Workspaces/pttu/spacetelescope.org/migration/csvfiles/postcarddata.csv'), PostCardDataMapping ),
    ArchiveMigrationTask( SpacetelescopeCSVDataSource( '/Users/luis/Workspaces/pttu/spacetelescope.org/migration/csvfiles/posterdata.csv'), PosterDataMapping ),
    ArchiveMigrationTask( SpacetelescopeCSVDataSource( '/Users/luis/Workspaces/pttu/spacetelescope.org/migration/csvfiles/presskitdata.csv'), PressKitDataMapping ),
    ArchiveMigrationTask( SpacetelescopeCSVDataSource( '/Users/luis/Workspaces/pttu/spacetelescope.org/migration/csvfiles/stickerdata.csv'), StickerDataMapping ),
    
    # Org
    #ArchiveMigrationTask( SpacetelescopeCSVDataSource( '/Users/luis/Workspaces/pttu/spacetelescope.org/migration/csvfiles/updatedata.csv'), AnnouncementDataMapping ),
    #ArchiveMigrationTask( SpacetelescopeCSVDataSource( '/Users/luis/Workspaces/pttu/spacetelescope.org/migration/csvfiles/conferenceposterdata.csv'), ConferencePosterDataMapping ),
    #ArchiveMigrationTask( SpacetelescopeCSVDataSource( '/Users/luis/Workspaces/pttu/spacetelescope.org/migration/csvfiles/logodata.csv'), LogoDataMapping ),
    #ArchiveMigrationTask( SpacetelescopeCSVDataSource( '/Users/luis/Workspaces/pttu/spacetelescope.org/migration/csvfiles/techdocsdata.csv'), TechnicalDocumentDataMapping ),
    
]


pagestasks = [
	PageInitializationTask(),
	PageMigrationTask( SpacetelescopePageDocument( 'about/further_information/presskits/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/further_information/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/further_information/links.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/further_information/literature.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/further_information/litterature.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/instruments/costar.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/instruments/acs.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/instruments/ghrs.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/instruments/fgs.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/instruments/foc.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/instruments/fos.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/instruments/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/instruments/hsp.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/instruments/nicmos.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/instruments/stis.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/instruments/wfpc1.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/instruments/wfpc2.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/instruments/wfc3.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/instruments/cos.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/instruments/wfc3_new.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/instruments/cos_new.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/instruments/fgs_new.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/instruments/cos_old.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/instruments/fgs_old.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/instruments/wfc3_old.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/electrical_systems.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/fact_sheet.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/gyroscopes.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/institutions.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/old_solar_panels.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/operations.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/orbit.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/solar_panels.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/spacecraft.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/gyroscopes_new.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/batteries_new.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/soft capture_new.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/batteries.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/gyroscopes_old.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/general/soft_capture.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/future_servicing_missions.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/aberration_problem.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/servicing_mission_3a.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/launch_1990.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/servicing_mission_1.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/servicing_mission_2.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/servicing_mission_3b.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/sm3a_live_coverage.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/sm3a_update1.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/sm3a_update10.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/sm3a_update11.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/sm3a_update12.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/sm3a_update2.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/sm3a_update3.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/sm3a_update4.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/sm3a_update5.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/sm3a_update6.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/sm3a_update7.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/sm3a_update8.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/sm3a_update9.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/sm3b_a_little_boost.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/sm3b_a_new_coat.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/sm3b_astronauts.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/sm3b_new_solar_panels.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/sm3b_nicmos_returns.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/the_man_behind_the_name.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/timeline.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/servicing_mission_4.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/trivia_2008.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/servicing_mission_4_new.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/stis_repair.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/acs_repair.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/esa.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/Tools_new.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/Crew_new.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/IMAX_new.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/thermal_new.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/servicing_mission_4_old.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/imax.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/tools.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/thermal.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/crew.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/sm4_timeline.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/history/sm4_tv.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'about/history/sm4blog/readme.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'about/history/sm4blog/wp-includes/js/tinymce/plugins/wpeditimage/editimage.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/glossary.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/faq.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about_us/evaluation/google_news.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about_us/evaluation/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about_us/evaluation/press_clippings.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about_us/evaluation/web_stats.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about_us/heic/european.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about_us/heic/group.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about_us/heic/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about_us/heic/mission.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about_us/heic/products.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about_us/heic/scientist_guidelines.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about_us/heic/students.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about_us/heic/world.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about_us/contact.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about_us/copyright.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about_us/hubblenews.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'about_us/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bin/utils/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bin/template_kids_corner.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bin/template_frontpage_bp.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bin/template_frontpage_bp3.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bin/template_frontpagebp4.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bin/template_about.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bin/template_about2.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bin/template_about_us.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bin/template_goodies.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bin/template_images.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bin/template_news.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bin/template_pressroom.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bin/template_projects.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bin/template_videos.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bin/template_frontpage.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bugs/doc/en/administration_guide.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bugs/doc/en/developers.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bugs/javascript/dev/projax/license.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bugs/javascript/min/projax/license.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bugs/library/adodb/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bugs/library/disposable/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bugs/library/nusoap/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bugs/library/utf8/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bugs/library/phpmailer/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bugs/library/projax/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'bugs/library/rssbuilder/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'goodies/art/submit_art.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'goodies/image_experience/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'goodies/interactive_hubble/index.html') ),
	PageMigrationTask( HTMLPageDocument( 'goodies/interactive_hubble/index_old.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'goodies/slideshows/flash/hubble_images_3/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'goodies/slideshows/flash/hubble_images_4/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'goodies/slideshows/flash/hubble_images_5/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'goodies/slideshows/flash/hubble_images_6/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'goodies/slideshows/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'goodies/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'goodies/orbit.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'goodies/tutorial/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'goodies/tutorial/index1.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'goodies/slideshows.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'goodies/ecards/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'goodies/ecards/xmas2006/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'goodies/mergingGalaxiesSite/mergingGalaxies.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'goodies/mergingGalaxiesSite/old/mergingGalaxies.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'hubbleshop/cvc_info.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'hubbleshop/freeorders.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'hubbleshop/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'hubbleshop/maintenance.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'hubbleshop/payment.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'hubbleshop/purchasing_steps.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'hubbleshop/shipping.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'hubbleshop/terms_conditions.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'hubbleshop/bulk_orders.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'contact.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'copyright.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'error_401.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'error_404.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'images/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'images/search.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'images/search2.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'integral/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'integral/index_old.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'kidsandteachers/exercises.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'kidsandteachers/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'kidsandteachers/submit_drawings.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/intern/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/workshop/billeder/Page.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/workshop/billeder/Page0002.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/workshop/billeder/Page0003.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/workshop/billeder/Page0004.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/workshop/billeder/Page0005.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/workshop/deltagere.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/workshop/form.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/workshop/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/workshop/indhold.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/workshop/indtryk.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/workshop/intro.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/workshop/praktisk.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/workshop/proceedings.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/workshop/program.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/workshop/regform.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/workshop/registration.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/workshop/tilmelding.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/index2.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/index2.shtml') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/index_old.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/intro.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/introduktion.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/litteratur.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/medlemmer.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'nvff/pios_dk.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'netscape.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'pressroom/embargo/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'pressroom/presskits/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'pressroom/crabfacts.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'pressroom/interview_possibilities.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'pressroom/broadcast_videos.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'pressroom/error_401.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'pressroom/image_formats.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'pressroom/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'pressroom/template.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'pressroom/video_formats.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'pressroom/mailinglist.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'pressroom/presscoverage.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/DVD/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/IAU_WG/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/anniversary/about_bob.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/anniversary/about_lars.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/anniversary/about_martin.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/anniversary/anniversary.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/anniversary/educational_material.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/anniversary/book.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/anniversary/credits.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/anniversary/events.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/anniversary/events2.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/anniversary/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/anniversary/index2.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/anniversary/movie_dvd.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/anniversary/outlets.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/anniversary/partners.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/anniversary/planeratirum_show.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/anniversary/planetaria.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/anniversary/planetarium_show.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/anniversary/poster.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/anniversary/press_meetings.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/anniversary/soundtrack.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/av_lab/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/credibility/credibility.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/credibility/credibility_interviews.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/denmark/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/bugs/doc/documentation.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/bugs/doc/faq.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/archives.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/blackwhitehelp.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/bugform.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/bugthanks.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/datasets.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/datateachers.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/download.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/download_v1.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/download_v2.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/eagledata.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/faq.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/fitsforeducation.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/fitsmailinglist.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/improc.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/knownissues.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/m12data.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/m17data.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/m31data.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/m35data.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/m42data.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/n11bdata.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/news.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/ngc1068data.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/ngc1569data.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/ngc5307data.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/ngc6302data.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/ngc6309data.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/ngc6652data.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/ngc6881data.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/roberts22data.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/robertsdata.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/specs.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/stepbystep.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/submit_images.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/teachersdata.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/userguide.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/userguide_v1.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/userimages.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/venusdata.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/index21.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/download_v21.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/download_v20.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/readme.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/readme21.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/index1.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/indexol.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/antennaedata.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/downloads_page.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/datasets_archives.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/knownissues_faq.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/download_v22.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/mosaicator.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/documents.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/download_v23.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/fits_liberator/v23files/releasenotes.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/cap2005.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/vo_images/improc.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/vo_images/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/web/article.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/web/article2.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/web/download.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/web/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/kiosk.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/iauga2006.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/seminars/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/socialnetworking/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'projects/iau_pressoffice/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'projects/python-xmp-toolkit/docs/appendix.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'projects/python-xmp-toolkit/docs/modindex.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'projects/python-xmp-toolkit/docs/developers.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'projects/python-xmp-toolkit/docs/genindex.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'projects/python-xmp-toolkit/docs/using.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'projects/python-xmp-toolkit/docs/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'projects/python-xmp-toolkit/docs/installation.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'projects/python-xmp-toolkit/docs/introduction.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'projects/python-xmp-toolkit/docs/reference.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'projects/python-xmp-toolkit/docs/search.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'q/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'q/thanks.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'science/composition_of_universe.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'science/age_size.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'science/black_holes.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'science/gravitational_lensing.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'science/deep_fields.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'science/europe_hubble.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'science/formation_of_stars.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'science/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'science/our_solar_system.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'science/stellar_evolution.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'science/protoplanetary_extrasolar.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/htdig/templates/nomatch.hubble.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/htdig/templates/wrapper.hubble.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/htdig/footer.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/htdig/footer.hubble.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/htdig/header.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/htdig/header.hubble.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/htdig/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/htdig/index.orig.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/htdig/long.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/htdig/nomatch.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/htdig/nomatch.hubble.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/htdig/short.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/htdig/syntax.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/htdig/wrapper.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/htdig/wrapper.hubble.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/htdig/common/header.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/htdig/common/footer.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/htdig/common/wrapper.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/htdig/common/nomatch.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/htdig/common/syntax.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/htdig/common/long.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/htdig/common/short.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/htdig/search.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/webcheck/badlinks.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/webcheck/external.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/webcheck/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/webcheck/navbar.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/webcheck/notchkd.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'search/webcheck/problems.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'xmm/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2006/heic0619-ngc6357/ngc6357.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/heic070x-ngc602/ngc602.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/ngc1672/ngc1672.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/abell2667/abell2667.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/GLgallery/glgallery.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/ngc4449/ngc4449.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/ngc4449/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/MergingGalaxies/merginggalaxies.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/MergingGalaxies/mergingGalaxiesSite/mergingGalaxies.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/GlobularGallery/globulargallery.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/PNgallery/pngallery.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/galaxies_zoo/galaxies_zoo.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/ngc2023_7023/ngc2023_7023.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/veil/veil.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/ngc2174/ngc2174.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/m74/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/ngc604/ngc604.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/ic2574/ic2574.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/star0537/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/heic070x-COSMOS/cosmos.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/holmberg_II/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/heic0703-ngc2440/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/heic0701-COSMOS/cosmos.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/ngc1398/ngc1398.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/ngc4402/ngc4402.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/ngc5253/ngc5253.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/CL0024+16/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/ngc3603/ngc3606.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/ngc3603/ngc3603.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/CL002416/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/m66/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/GC_demography/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/GC_demographics/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/ngc891/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/n11/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/ngc1275/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/hcg031/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/ngc1132/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/ngc7173/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/heic0716-izw18/izw18.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/methane/methane.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/arp87/arp87.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/cosmoslenses/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/heic0719-m74/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2007/exo_hazes/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/contracts.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/index2.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/IYA/iyalogos.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/IYA/logos.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/IYA/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/IYA/Current.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/IYA/Current_02.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/IYA/newlogos.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/IYA/final.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/colour_tests.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/colourtests/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/iauimages.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/designkits.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/wfc3_ero/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/cosmoslenses/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/ngc1132/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/m66/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/ngc1275/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/PNgallery/pngallery.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/GLgallery/abell1703/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/GLgallery/glgallery.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/ngc2023_7023/ngc2023_7023.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/ngc2174/ngc2174.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/star0537/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/galaxies_zoo/galaxies_zoo.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/holmberg_II/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/ngc604/ngc604.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/ic2574/ic2574.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/GlobularGallery/globulargallery.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/ngc5253/ngc5253.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/ngc891/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/n11/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/hcg031/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/ngc7173/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/exo_hazes/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/hcg_007/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/coma/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/lecavallier/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/omegacen/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/ngc3314/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/ngc2366/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/ic2233/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/ngc4911/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/ngc4921/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/abell1703/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/antennae_distance/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/ngc2623/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/ngc2397/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/bullet2/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/ngc253/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/ngc4183/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/ngc4631/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/mj257/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/edgeon/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/edgeon/ic2233/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/eso056/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/ngc6441/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/RPS_gallery/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/fomalhaut/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/sm4/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/ngc7049/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/ngc4696/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/heic0820_hubble_return/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/eso306/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/ngc1073/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/2008/CO2/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200707.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200707.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200708.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200708.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/downloads/2004.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/downloads/2005.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/downloads/2006.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/downloads/liberatordownloads.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/downloads/vodcasts2007.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/downloads/2007.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/downloads/2008.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/downloads/vodcasts2008.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/downloads/2009.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/downloads/vodcasts2009.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200801.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200801.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200802.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200802.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200803.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200803.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200804.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200804.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200805.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200805.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200806.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200806.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200807.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200807.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/agent_200807.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200709.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200709.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200601.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200601.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200602.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200602.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200603.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200603.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200604.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200604.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200605.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200710.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200605.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200606.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200606.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200607.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200607.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200608.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200608.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200609.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200609.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200610.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200610.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200611.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200611.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200612.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200612.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200701.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200701.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200702.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200702.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200703.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200703.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200704.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200704.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200705.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200705.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200706.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200706.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/agent_200709.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200710.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/agent_200710.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/agent_200708.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200711.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200711.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200712.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200712.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200808.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200808.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/agent_200808.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200809.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200809.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/agent_200809.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200810.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200810.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/agent_200810.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200811.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200811.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/agent_200811.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200812.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200812.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/agent_200812.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200901.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200901.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/agent_200901.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200902.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200902.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/agent_200902.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200903.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200903.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/agent_200903.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200904.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200904.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/agent_200904.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200905.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200905.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200906.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200906.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/usage_200907.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats/url_200907.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/cosmos_viz_frankel.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/internal_computers.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/internal_stats.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/internal_iya.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/internal_newsportals.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/internal_shop.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/internal_vamp.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/internal_vodcasts.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/internal_capjournal.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/internal_websites.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/internal_collaborative.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/internal_hr.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/internal_hubblereleases.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/internal_fitsliberator.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/internal_personel.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/internal_personnel.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/internal_mailinglists.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/internal_web_development.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/internal_addresses.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/internal_web_infrastructure.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats_tmp/usage_200804.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats_tmp/url_200804.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats_tmp/usage_200901.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats_tmp/url_200901.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats_tmp/usage_200806.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats_tmp/url_200806.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats_tmp/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/webstats_tmp/agent_200901.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/internal_iaureleases.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/internal_iyareleases.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal/internal_iauweb_deployment_howto.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'sitemap.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/DVD/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/kx76.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ldwarf.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/lynx.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/m100mosaic.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/m101.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/m17.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/m22.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/m42.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/m42rerel.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/m74.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/m81_sn.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc1068.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc1275.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc1512.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc1569.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc1705.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc1850.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc2080.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc265_290.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc2903.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc3081.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc346.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc346_2.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc3631.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc3918.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc3982.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc4365.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/z7.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/lh95.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/gc.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/n520.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/miley_spider.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/esa_eso_003_pages.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/epsilon_eridani.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/sweeps.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/approval.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/atomsforpeace.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/avoqso.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/boomerang.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/casa.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/cenamos.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/circumbin.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/contracts.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/crab.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/cygloop.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/deep_impact_post.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/deep_impact_pre.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/distant_clusters.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/elinedwarf.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/exoatm.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/fits.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/fosrecal.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/galaxy.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/gl618.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/goals.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/hdf3d.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/hdfdwarfs.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/heic0113.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/hen3_1475.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/hen401.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/hstcass.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/hubble5.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/hubblev.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ic4634.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/integral.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/m82.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/m82mos.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/mass_map.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/mission.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/mz3.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/n11a.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/n11b.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/n44f.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/n63.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc4449.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc454.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc4945.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc5307.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc5882.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc5979.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc602.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc6210.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc6302.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc6326.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/index2.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc6537.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc6543.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc6621.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc6652.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc6881.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc6888.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc7026.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc7354.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc7673.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/order_form.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/pipeline.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/poodle.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/products.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/pulsar.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/qso_nohost.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/qsoiron.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/quadruple_qso.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/roberts22.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/rotten2.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/saturn_aurora.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/sflmc.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/siriusb.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/sn1994d.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/sn_bh.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/stephensquintet.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/submm.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/tarantula.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/tycho_sn.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/v838.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/v838again_again.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/veil.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/venus.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/galaxieszoo.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/antennae.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/abell1703.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc4522.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'internal_old/ngc6357.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'googlea95441ee32fbe5c8.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'testphp/web20.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/usage_200701.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/usage_200612.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/a9/usage_200808.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/a9/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/a9/usage_200807.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/sep/bugreport.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/sep/www2009/days0909.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/sep/www2009/topurl0909.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/sep/www2009/topdom0909.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/sep/www2009/rsites0909.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/sep/www2009/lsites0909.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/sep/www2009/jsnav.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/sep/www2009/files0909.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/sep/www2009/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/sep/www2009/country0909.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/sep/www2009/nav0909.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/sep/www2009/avload0909.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/sep/www2009/totals0909.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/sep/www2009/stats0909.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/sep/www2009/lfiles0909.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/sep/www2009/rfiles0909.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/sep/www2009/sites0909.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/sep/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/usage_200601.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/usage_200602.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/usage_200603.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/usage_200604.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/usage_200605.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/usage_200606.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/usage_200607.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/usage_200608.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/usage_200609.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/usage_200610.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/usage_200611.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/usage_200702.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/usage_200703.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/usage_200704.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/usage_200705.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/usage_200706.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/usage_200707.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/usage_200708.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'mn/usage_200709.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'googlead94a0599adf8109.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'index_test.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'maptest/examples/zoom_and_description/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'maptest/examples/zoomifyer/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'maptest/examples/map_chart/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'maptest/examples/javascript_control/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'maptest/examples/drill_down/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'maptest/examples/custom_areas/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'maptest/examples/countries_usa/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'maptest/examples/countries_japan/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'maptest/examples/countries_australia/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'tests/index.html') ),
	PageMigrationTask( SpacetelescopePageDocument( 'jobs/index.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'unavailable.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'test/error.html') ),
#	PageMigrationTask( SpacetelescopePageDocument( 'google34e371fb40a60c65.html') ), 
]

tasks = choose_tasks()

if __name__ == "__main__":
	"""
	Run complete migration 
	"""
	run_migration( conf, tasks )