class archive_settings:
    CDROM_ROOT = 'archives/cdroms'
    POSTER_ROOT = 'archives/posters'
    CONFERENCE_POSTER_ROOT = 'archives/conference_posters'
    LOGO_ROOT = 'archives/logos'
    BOOK_ROOT = 'archives/books'
    BROCHURE_ROOT = 'archives/brochures'
    CALENDAR_ROOT = 'archives/calendars'
    PRESSKIT_ROOT = 'archives/presskits'
    STICKER_ROOT = 'archives/stickers'
    TECHDOC_ROOT = 'archives/techdocs'
    MERCHANDISE_ROOT = 'archives/merchandise'
    SLIDESHOW_ROOT = 'archives/slideshows'
    ANNOUNCEMENT_ROOT = 'archives/updates'
    NEWSLETTER_ROOT = 'archives/news'
    FITS_IMAGE_ROOT = 'archives/fitsimages'
    KIDS_DRAWING_ROOT = 'archives/drawings'
    EDUMATERIAL_ROOT = 'archives/education'
    ONLINE_ART_ROOT = 'archives/art'
    ONLINE_ART_AUTHOR_ROOT = 'archives/artists'
    POSTCARD_ROOT = 'archives/postcards'
    EXHIBITION_ROOT = 'archives/exhibitions'
    USER_VIDEO_ROOT = 'archives/user_videos'
    PRINT_LAYOUT_ROOT = 'archives/printlayouts'
    
    
