class archive_settings:
    CDROM_ROOT = 'cdroms'
    POSTER_ROOT = 'posters'
    CONFERENCE_POSTER_ROOT = 'conference_posters'
    LOGO_ROOT = 'logos'
    BOOK_ROOT = 'books'
    BROCHURE_ROOT = 'brochures'
    CALENDAR_ROOT = 'calendars'
    PRESSKIT_ROOT = 'presskits'
    STICKER_ROOT = 'stickers'
    TECHDOC_ROOT = 'techdocs'
    MERCHANDISE_ROOT = 'merchandise'
    SLIDESHOW_ROOT = 'slideshows'
    ANNOUNCEMENT_ROOT = 'updates'
    NEWSLETTER_ROOT = 'news'
    FITS_IMAGE_ROOT = 'fitsimages'
    KIDS_DRAWING_ROOT = 'drawings'
    EDUMATERIAL_ROOT = 'education'
    ONLINE_ART_ROOT = 'art'
    ONLINE_ART_AUTHOR_ROOT = 'artists'
    POSTCARD_ROOT = 'postcards'
    EXHIBITION_ROOT = 'exhibitions'
    USER_VIDEO_ROOT = 'user_videos'
    PRINT_LAYOUT_ROOT = 'printlayouts'
    
    
