BEGIN;
RENAME TABLE `archives_educationalmaterial` TO `products_educationalmaterial`;
RENAME TABLE `archives_cdrom` TO `products_kidsdrawing`;
RENAME TABLE `archives_book` TO `products_book`;
RENAME TABLE `archives_brochure` TO `products_brochure`;
RENAME TABLE `archives_newsletter` TO `products_newsletter`;
RENAME TABLE `archives_postcard` TO `products_postcard`;
RENAME TABLE `archives_poster` TO `products_poster`;
RENAME TABLE `archives_presskit` TO `products_presskit`;
RENAME TABLE `archives_sticker` TO `products_sticker`;
RENAME TABLE `archives_conferenceposter` TO `products_conferenceposter`;
RENAME TABLE `archives_logo` TO `products_logo`;
RENAME TABLE `archives_technicaldocument` TO `products_technicaldocument`;
RENAME TABLE `archives_calendar` TO `products_calendar`;
RENAME TABLE `archives_onlineartauthor` TO `products_onlineartauthor`;
RENAME TABLE `archives_onlineart` TO `products_onlineart`;
RENAME TABLE `archives_slideshow` TO `products_slideshow`;
RENAME TABLE `archives_exhibition` TO `products_exhibition`;
RENAME TABLE `archives_fitsimage` TO `products_fitsimage`;
RENAME TABLE `archives_uservideo` TO `products_uservideo`;
RENAME TABLE `archives_presentation` TO `products_presentation`;

COMMIT;